/*
AvaTax API

REST interface to Avalara's enterprise tax service, AvaTax.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CancelTransactionModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelTransactionModel{}

// CancelTransactionModel A request to cancel a previously created transaction
type CancelTransactionModel struct {
	// Please specify the reason for cancelling this transaction
	Code *string `json:"code,omitempty"`
}

// NewCancelTransactionModel instantiates a new CancelTransactionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelTransactionModel() *CancelTransactionModel {
	this := CancelTransactionModel{}
	return &this
}

// NewCancelTransactionModelWithDefaults instantiates a new CancelTransactionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelTransactionModelWithDefaults() *CancelTransactionModel {
	this := CancelTransactionModel{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CancelTransactionModel) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelTransactionModel) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CancelTransactionModel) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CancelTransactionModel) SetCode(v string) {
	o.Code = &v
}

func (o CancelTransactionModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelTransactionModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableCancelTransactionModel struct {
	value *CancelTransactionModel
	isSet bool
}

func (v NullableCancelTransactionModel) Get() *CancelTransactionModel {
	return v.value
}

func (v *NullableCancelTransactionModel) Set(val *CancelTransactionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelTransactionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelTransactionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelTransactionModel(val *CancelTransactionModel) *NullableCancelTransactionModel {
	return &NullableCancelTransactionModel{value: val, isSet: true}
}

func (v NullableCancelTransactionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelTransactionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


